//! This code was AUTOGENERATED using the Codama library.
use carbon_core::borsh;
/// Tracks exponential moving averages (EMAs) for the last observed price.
/// - `symmetric`: standard two-way EMA (exponential price growth and decay)
/// - `directional`: one-way bottom-up asymmetric EMA (exponential price growth, but snaps instantly on price drops)

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct LastPriceEMA {
    pub symmetric: u64,
    pub directional: u64,
}

