//! This code was AUTOGENERATED using the Codama library.
use carbon_core::borsh;
use crate::types::EventMetadata;
use solana_pubkey::Pubkey;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, borsh::BorshDeserialize, PartialEq)]
pub struct PairCreatedEvent {
    pub token0: Pubkey,
    pub token1: Pubkey,
    pub lp_mint: Pubkey,
    pub token0_decimals: u8,
    pub token1_decimals: u8,
    pub rate_model: Pubkey,
    pub swap_fee_bps: u16,
    pub half_life: u64,
    pub fixed_cf_bps: Option<u16>,
    pub params_hash: [u8; 32],
    pub version: u8,
    pub metadata: EventMetadata,
}

