//! This code was AUTOGENERATED using the Codama library.
pub mod add_collateral_row;
pub mod add_liquidity_row;
pub mod borrow_row;
pub mod claim_protocol_fees_row;
pub mod distribute_tokens_row;
pub mod flashloan_row;
pub mod init_futarchy_authority_row;
pub mod initialize_row;
pub mod liquidate_row;
pub mod remove_collateral_row;
pub mod remove_liquidity_row;
pub mod repay_row;
pub mod swap_row;
pub mod update_futarchy_authority_row;
pub mod update_protocol_revenue_row;
pub mod view_pair_data_row;
pub mod view_user_position_data_row;
pub mod cpi_event_row;

pub use self::add_collateral_row::*;
pub use self::add_liquidity_row::*;
pub use self::borrow_row::*;
pub use self::claim_protocol_fees_row::*;
pub use self::distribute_tokens_row::*;
pub use self::flashloan_row::*;
pub use self::init_futarchy_authority_row::*;
pub use self::initialize_row::*;
pub use self::liquidate_row::*;
pub use self::remove_collateral_row::*;
pub use self::remove_liquidity_row::*;
pub use self::repay_row::*;
pub use self::swap_row::*;
pub use self::update_futarchy_authority_row::*;
pub use self::update_protocol_revenue_row::*;
pub use self::view_pair_data_row::*;
pub use self::view_user_position_data_row::*;
pub use self::cpi_event_row::*;

use super::OmnipairInstruction;

pub struct OmnipairInstructionsMigration;

impl sqlx_migrator::Migration<sqlx::Postgres> for OmnipairInstructionsMigration {
    fn app(&self) -> &str {
        "omnipair"
    }

    fn name(&self) -> &str {
        "omnipair_instructions"
    }

    fn operations(&self) -> Vec<Box<dyn sqlx_migrator::Operation<sqlx::Postgres>>> {
        vec![
            Box::new(AddCollateralMigrationOperation),
            Box::new(AddLiquidityMigrationOperation),
            Box::new(BorrowMigrationOperation),
            Box::new(ClaimProtocolFeesMigrationOperation),
            Box::new(DistributeTokensMigrationOperation),
            Box::new(FlashloanMigrationOperation),
            Box::new(InitFutarchyAuthorityMigrationOperation),
            Box::new(InitializeMigrationOperation),
            Box::new(LiquidateMigrationOperation),
            Box::new(RemoveCollateralMigrationOperation),
            Box::new(RemoveLiquidityMigrationOperation),
            Box::new(RepayMigrationOperation),
            Box::new(SwapMigrationOperation),
            Box::new(UpdateFutarchyAuthorityMigrationOperation),
            Box::new(UpdateProtocolRevenueMigrationOperation),
            Box::new(ViewPairDataMigrationOperation),
            Box::new(ViewUserPositionDataMigrationOperation),
            Box::new(CpiEventMigrationOperation),
        ]
    }

    fn parents(&self) -> Vec<Box<dyn sqlx_migrator::Migration<sqlx::Postgres>>> {
        vec![]
    }
}

pub struct OmnipairInstructionWithMetadata(pub OmnipairInstruction, pub carbon_core::instruction::InstructionMetadata);

impl From<(OmnipairInstruction, carbon_core::instruction::InstructionMetadata)> for OmnipairInstructionWithMetadata {
    fn from(value: (OmnipairInstruction, carbon_core::instruction::InstructionMetadata)) -> Self {
        OmnipairInstructionWithMetadata(value.0, value.1)
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Insert for OmnipairInstructionWithMetadata {
    async fn insert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        let OmnipairInstructionWithMetadata(instruction, metadata) = self;
        match instruction {
            OmnipairInstruction::AddCollateral(instruction) => {
                let row = add_collateral_row::AddCollateralRow::from_parts(instruction.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
            OmnipairInstruction::AddLiquidity(instruction) => {
                let row = add_liquidity_row::AddLiquidityRow::from_parts(instruction.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
            OmnipairInstruction::Borrow(instruction) => {
                let row = borrow_row::BorrowRow::from_parts(instruction.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
            OmnipairInstruction::ClaimProtocolFees(instruction) => {
                let row = claim_protocol_fees_row::ClaimProtocolFeesRow::from_parts(instruction.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
            OmnipairInstruction::DistributeTokens(instruction) => {
                let row = distribute_tokens_row::DistributeTokensRow::from_parts(instruction.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
            OmnipairInstruction::Flashloan(instruction) => {
                let row = flashloan_row::FlashloanRow::from_parts(instruction.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
            OmnipairInstruction::InitFutarchyAuthority(instruction) => {
                let row = init_futarchy_authority_row::InitFutarchyAuthorityRow::from_parts(instruction.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
            OmnipairInstruction::Initialize(instruction) => {
                let row = initialize_row::InitializeRow::from_parts(instruction.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
            OmnipairInstruction::Liquidate(instruction) => {
                let row = liquidate_row::LiquidateRow::from_parts(instruction.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
            OmnipairInstruction::RemoveCollateral(instruction) => {
                let row = remove_collateral_row::RemoveCollateralRow::from_parts(instruction.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
            OmnipairInstruction::RemoveLiquidity(instruction) => {
                let row = remove_liquidity_row::RemoveLiquidityRow::from_parts(instruction.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
            OmnipairInstruction::Repay(instruction) => {
                let row = repay_row::RepayRow::from_parts(instruction.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
            OmnipairInstruction::Swap(instruction) => {
                let row = swap_row::SwapRow::from_parts(instruction.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
            OmnipairInstruction::UpdateFutarchyAuthority(instruction) => {
                let row = update_futarchy_authority_row::UpdateFutarchyAuthorityRow::from_parts(instruction.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
            OmnipairInstruction::UpdateProtocolRevenue(instruction) => {
                let row = update_protocol_revenue_row::UpdateProtocolRevenueRow::from_parts(instruction.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
            OmnipairInstruction::ViewPairData(instruction) => {
                let row = view_pair_data_row::ViewPairDataRow::from_parts(instruction.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
            OmnipairInstruction::ViewUserPositionData(instruction) => {
                let row = view_user_position_data_row::ViewUserPositionDataRow::from_parts(instruction.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
            OmnipairInstruction::CpiEvent(instruction) => {
                let row = cpi_event_row::CpiEventRow::from_parts(instruction.clone(), metadata.clone());
                row.insert(pool).await?;
                Ok(())
            }
        }
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Upsert for OmnipairInstructionWithMetadata {
    async fn upsert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        let OmnipairInstructionWithMetadata(instruction, metadata) = self;
        match instruction {
            OmnipairInstruction::AddCollateral(instruction) => {
                let row = add_collateral_row::AddCollateralRow::from_parts(instruction.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
            OmnipairInstruction::AddLiquidity(instruction) => {
                let row = add_liquidity_row::AddLiquidityRow::from_parts(instruction.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
            OmnipairInstruction::Borrow(instruction) => {
                let row = borrow_row::BorrowRow::from_parts(instruction.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
            OmnipairInstruction::ClaimProtocolFees(instruction) => {
                let row = claim_protocol_fees_row::ClaimProtocolFeesRow::from_parts(instruction.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
            OmnipairInstruction::DistributeTokens(instruction) => {
                let row = distribute_tokens_row::DistributeTokensRow::from_parts(instruction.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
            OmnipairInstruction::Flashloan(instruction) => {
                let row = flashloan_row::FlashloanRow::from_parts(instruction.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
            OmnipairInstruction::InitFutarchyAuthority(instruction) => {
                let row = init_futarchy_authority_row::InitFutarchyAuthorityRow::from_parts(instruction.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
            OmnipairInstruction::Initialize(instruction) => {
                let row = initialize_row::InitializeRow::from_parts(instruction.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
            OmnipairInstruction::Liquidate(instruction) => {
                let row = liquidate_row::LiquidateRow::from_parts(instruction.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
            OmnipairInstruction::RemoveCollateral(instruction) => {
                let row = remove_collateral_row::RemoveCollateralRow::from_parts(instruction.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
            OmnipairInstruction::RemoveLiquidity(instruction) => {
                let row = remove_liquidity_row::RemoveLiquidityRow::from_parts(instruction.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
            OmnipairInstruction::Repay(instruction) => {
                let row = repay_row::RepayRow::from_parts(instruction.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
            OmnipairInstruction::Swap(instruction) => {
                let row = swap_row::SwapRow::from_parts(instruction.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
            OmnipairInstruction::UpdateFutarchyAuthority(instruction) => {
                let row = update_futarchy_authority_row::UpdateFutarchyAuthorityRow::from_parts(instruction.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
            OmnipairInstruction::UpdateProtocolRevenue(instruction) => {
                let row = update_protocol_revenue_row::UpdateProtocolRevenueRow::from_parts(instruction.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
            OmnipairInstruction::ViewPairData(instruction) => {
                let row = view_pair_data_row::ViewPairDataRow::from_parts(instruction.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
            OmnipairInstruction::ViewUserPositionData(instruction) => {
                let row = view_user_position_data_row::ViewUserPositionDataRow::from_parts(instruction.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
            OmnipairInstruction::CpiEvent(instruction) => {
                let row = cpi_event_row::CpiEventRow::from_parts(instruction.clone(), metadata.clone());
                row.upsert(pool).await?;
                Ok(())
            }
        }
    }
}
