//! This code was AUTOGENERATED using the Codama library.

pub mod adjust_collateral_event;
pub mod adjust_debt_event;
pub mod adjust_liquidity_event;
pub mod burn_event;
pub mod flashloan_event;
pub mod mint_event;
pub mod pair_created_event;
pub mod swap_event;
pub mod update_pair_event;
pub mod user_liquidity_position_updated_event;
pub mod user_position_created_event;
pub mod user_position_liquidated_event;
pub mod user_position_updated_event;

