//! This code was AUTOGENERATED using the Codama library.
use carbon_core::account::AccountMetadata;
use carbon_core::postgres::metadata::AccountRowMetadata;
use carbon_core::postgres::primitives::Pubkey;
use carbon_core::postgres::primitives::U8;
use crate::types::RevenueDistribution;
use crate::types::RevenueRecipients;
use crate::types::RevenueShare;

#[derive(sqlx::FromRow, Debug, Clone)]
pub struct FutarchyAuthorityRow {
    #[sqlx(flatten)]
    pub account_metadata: AccountRowMetadata,
    pub version: U8,
    pub authority: Pubkey,
    pub recipients: sqlx::types::Json<RevenueRecipients>,
    pub revenue_share: sqlx::types::Json<RevenueShare>,
    pub revenue_distribution: sqlx::types::Json<RevenueDistribution>,
    pub bump: U8,
}

impl FutarchyAuthorityRow {
    pub fn from_parts(source: crate::accounts::futarchy_authority::FutarchyAuthority, metadata: AccountMetadata) -> Self {
        Self {
            account_metadata: metadata.into(),
            version: source.version.into(),
            authority: source.authority.into(),
            recipients: sqlx::types::Json(source.recipients.into()),
            revenue_share: sqlx::types::Json(source.revenue_share.into()),
            revenue_distribution: sqlx::types::Json(source.revenue_distribution.into()),
            bump: source.bump.into(),
        }
    }
}

impl TryFrom<FutarchyAuthorityRow> for crate::accounts::futarchy_authority::FutarchyAuthority {
    type Error = carbon_core::error::Error;
    fn try_from(source: FutarchyAuthorityRow) -> Result<Self, Self::Error> {
        Ok(Self {
            version: source.version.try_into().map_err(|_| carbon_core::error::Error::Custom("Failed to convert value from postgres primitive".to_string()))?,
            authority: *source.authority,
            recipients: source.recipients.0,
            revenue_share: source.revenue_share.0,
            revenue_distribution: source.revenue_distribution.0,
            bump: source.bump.try_into().map_err(|_| carbon_core::error::Error::Custom("Failed to convert value from postgres primitive".to_string()))?,
        })
    }
}

impl carbon_core::postgres::operations::Table for crate::accounts::futarchy_authority::FutarchyAuthority {
    fn table() -> &'static str {
        "futarchy_authority_account"
    }

    fn columns() -> Vec<&'static str> {
        vec![
            "__pubkey",
            "__slot",
            "version",
            "authority",
            "recipients",
            "revenue_share",
            "revenue_distribution",
            "bump",
        ]
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Insert for FutarchyAuthorityRow {
    async fn insert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(r#"
            INSERT INTO futarchy_authority_account (
                "version",
                "authority",
                "recipients",
                "revenue_share",
                "revenue_distribution",
                "bump",
                __pubkey, __slot
            ) VALUES (
                $1, $2, $3, $4, $5, $6, $7, $8
            )"#)
        .bind(self.version.clone())
        .bind(self.authority.clone())
        .bind(self.recipients.clone())
        .bind(self.revenue_share.clone())
        .bind(self.revenue_distribution.clone())
        .bind(self.bump.clone())
        .bind(self.account_metadata.pubkey.clone())
        .bind(self.account_metadata.slot.clone())
        .execute(pool).await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Upsert for FutarchyAuthorityRow {
    async fn upsert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(r#"INSERT INTO futarchy_authority_account (
                "version",
                "authority",
                "recipients",
                "revenue_share",
                "revenue_distribution",
                "bump",
                __pubkey, __slot
            ) VALUES (
                $1, $2, $3, $4, $5, $6, $7, $8
            ) ON CONFLICT (
                __pubkey
            ) DO UPDATE SET
                "version" = EXCLUDED."version",
                "authority" = EXCLUDED."authority",
                "recipients" = EXCLUDED."recipients",
                "revenue_share" = EXCLUDED."revenue_share",
                "revenue_distribution" = EXCLUDED."revenue_distribution",
                "bump" = EXCLUDED."bump",
                __slot = EXCLUDED.__slot
            "#)
        .bind(self.version.clone())
        .bind(self.authority.clone())
        .bind(self.recipients.clone())
        .bind(self.revenue_share.clone())
        .bind(self.revenue_distribution.clone())
        .bind(self.bump.clone())
        .bind(self.account_metadata.pubkey)
        .bind(self.account_metadata.slot.clone())
        .execute(pool).await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Delete for FutarchyAuthorityRow {
    type Key = carbon_core::postgres::primitives::Pubkey;

    async fn delete(key: Self::Key, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(r#"DELETE FROM futarchy_authority_account WHERE
                __pubkey = $1
            "#)
        .bind(key)
        .execute(pool).await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::LookUp for FutarchyAuthorityRow {
    type Key = carbon_core::postgres::primitives::Pubkey;

    async fn lookup(key: Self::Key, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<Option<Self>> {
        let row = sqlx::query_as(r#"SELECT * FROM futarchy_authority_account WHERE
                __pubkey = $1
            "#)
        .bind(key)
        .fetch_optional(pool).await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(row)
    }
}

pub struct FutarchyAuthorityMigrationOperation;

#[async_trait::async_trait]
impl sqlx_migrator::Operation<sqlx::Postgres> for FutarchyAuthorityMigrationOperation {
    async fn up(&self, connection: &mut sqlx::PgConnection) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(r#"CREATE TABLE IF NOT EXISTS futarchy_authority_account (
                -- Account data
                "version" INT2 NOT NULL,
                "authority" BYTEA NOT NULL,
                "recipients" JSONB NOT NULL,
                "revenue_share" JSONB NOT NULL,
                "revenue_distribution" JSONB NOT NULL,
                "bump" INT2 NOT NULL,
                -- Account metadata
                __pubkey BYTEA NOT NULL,
                __slot NUMERIC(20),
                PRIMARY KEY (__pubkey)
            )"#).execute(connection).await?;
        Ok(())
    }

    async fn down(&self, connection: &mut sqlx::PgConnection) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(r#"DROP TABLE IF EXISTS futarchy_authority_account"#).execute(connection).await?;
        Ok(())
    }
}
