//! This code was AUTOGENERATED using the Codama library.
use carbon_core::account::AccountMetadata;
use carbon_core::postgres::metadata::AccountRowMetadata;
use carbon_core::postgres::primitives::U64;

#[derive(sqlx::FromRow, Debug, Clone)]
pub struct RateModelRow {
    #[sqlx(flatten)]
    pub account_metadata: AccountRowMetadata,
    pub exp_rate: U64,
    pub target_util_start: U64,
    pub target_util_end: U64,
}

impl RateModelRow {
    pub fn from_parts(source: crate::accounts::rate_model::RateModel, metadata: AccountMetadata) -> Self {
        Self {
            account_metadata: metadata.into(),
            exp_rate: source.exp_rate.into(),
            target_util_start: source.target_util_start.into(),
            target_util_end: source.target_util_end.into(),
        }
    }
}

impl TryFrom<RateModelRow> for crate::accounts::rate_model::RateModel {
    type Error = carbon_core::error::Error;
    fn try_from(source: RateModelRow) -> Result<Self, Self::Error> {
        Ok(Self {
            exp_rate: *source.exp_rate,
            target_util_start: *source.target_util_start,
            target_util_end: *source.target_util_end,
        })
    }
}

impl carbon_core::postgres::operations::Table for crate::accounts::rate_model::RateModel {
    fn table() -> &'static str {
        "rate_model_account"
    }

    fn columns() -> Vec<&'static str> {
        vec![
            "__pubkey",
            "__slot",
            "exp_rate",
            "target_util_start",
            "target_util_end",
        ]
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Insert for RateModelRow {
    async fn insert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(r#"
            INSERT INTO rate_model_account (
                "exp_rate",
                "target_util_start",
                "target_util_end",
                __pubkey, __slot
            ) VALUES (
                $1, $2, $3, $4, $5
            )"#)
        .bind(self.exp_rate.clone())
        .bind(self.target_util_start.clone())
        .bind(self.target_util_end.clone())
        .bind(self.account_metadata.pubkey.clone())
        .bind(self.account_metadata.slot.clone())
        .execute(pool).await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Upsert for RateModelRow {
    async fn upsert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(r#"INSERT INTO rate_model_account (
                "exp_rate",
                "target_util_start",
                "target_util_end",
                __pubkey, __slot
            ) VALUES (
                $1, $2, $3, $4, $5
            ) ON CONFLICT (
                __pubkey
            ) DO UPDATE SET
                "exp_rate" = EXCLUDED."exp_rate",
                "target_util_start" = EXCLUDED."target_util_start",
                "target_util_end" = EXCLUDED."target_util_end",
                __slot = EXCLUDED.__slot
            "#)
        .bind(self.exp_rate.clone())
        .bind(self.target_util_start.clone())
        .bind(self.target_util_end.clone())
        .bind(self.account_metadata.pubkey)
        .bind(self.account_metadata.slot.clone())
        .execute(pool).await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Delete for RateModelRow {
    type Key = carbon_core::postgres::primitives::Pubkey;

    async fn delete(key: Self::Key, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(r#"DELETE FROM rate_model_account WHERE
                __pubkey = $1
            "#)
        .bind(key)
        .execute(pool).await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::LookUp for RateModelRow {
    type Key = carbon_core::postgres::primitives::Pubkey;

    async fn lookup(key: Self::Key, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<Option<Self>> {
        let row = sqlx::query_as(r#"SELECT * FROM rate_model_account WHERE
                __pubkey = $1
            "#)
        .bind(key)
        .fetch_optional(pool).await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(row)
    }
}

pub struct RateModelMigrationOperation;

#[async_trait::async_trait]
impl sqlx_migrator::Operation<sqlx::Postgres> for RateModelMigrationOperation {
    async fn up(&self, connection: &mut sqlx::PgConnection) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(r#"CREATE TABLE IF NOT EXISTS rate_model_account (
                -- Account data
                "exp_rate" NUMERIC(20) NOT NULL,
                "target_util_start" NUMERIC(20) NOT NULL,
                "target_util_end" NUMERIC(20) NOT NULL,
                -- Account metadata
                __pubkey BYTEA NOT NULL,
                __slot NUMERIC(20),
                PRIMARY KEY (__pubkey)
            )"#).execute(connection).await?;
        Ok(())
    }

    async fn down(&self, connection: &mut sqlx::PgConnection) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(r#"DROP TABLE IF EXISTS rate_model_account"#).execute(connection).await?;
        Ok(())
    }
}
