//! This code was AUTOGENERATED using the Codama library.
use carbon_core::account::AccountMetadata;
use carbon_core::postgres::metadata::AccountRowMetadata;
use carbon_core::postgres::primitives::Pubkey;
use carbon_core::postgres::primitives::U128;
use carbon_core::postgres::primitives::U16;
use carbon_core::postgres::primitives::U64;
use carbon_core::postgres::primitives::U8;

#[derive(sqlx::FromRow, Debug, Clone)]
pub struct UserPositionRow {
    #[sqlx(flatten)]
    pub account_metadata: AccountRowMetadata,
    pub owner: Pubkey,
    pub pair: Pubkey,
    pub collateral0_applied_min_cf_bps: U16,
    pub collateral1_applied_min_cf_bps: U16,
    pub collateral0: U64,
    pub collateral1: U64,
    pub debt0_shares: U128,
    pub debt1_shares: U128,
    pub bump: U8,
}

impl UserPositionRow {
    pub fn from_parts(source: crate::accounts::user_position::UserPosition, metadata: AccountMetadata) -> Self {
        Self {
            account_metadata: metadata.into(),
            owner: source.owner.into(),
            pair: source.pair.into(),
            collateral0_applied_min_cf_bps: source.collateral0_applied_min_cf_bps.into(),
            collateral1_applied_min_cf_bps: source.collateral1_applied_min_cf_bps.into(),
            collateral0: source.collateral0.into(),
            collateral1: source.collateral1.into(),
            debt0_shares: source.debt0_shares.into(),
            debt1_shares: source.debt1_shares.into(),
            bump: source.bump.into(),
        }
    }
}

impl TryFrom<UserPositionRow> for crate::accounts::user_position::UserPosition {
    type Error = carbon_core::error::Error;
    fn try_from(source: UserPositionRow) -> Result<Self, Self::Error> {
        Ok(Self {
            owner: *source.owner,
            pair: *source.pair,
            collateral0_applied_min_cf_bps: source.collateral0_applied_min_cf_bps.try_into().map_err(|_| carbon_core::error::Error::Custom("Failed to convert value from postgres primitive".to_string()))?,
            collateral1_applied_min_cf_bps: source.collateral1_applied_min_cf_bps.try_into().map_err(|_| carbon_core::error::Error::Custom("Failed to convert value from postgres primitive".to_string()))?,
            collateral0: *source.collateral0,
            collateral1: *source.collateral1,
            debt0_shares: *source.debt0_shares,
            debt1_shares: *source.debt1_shares,
            bump: source.bump.try_into().map_err(|_| carbon_core::error::Error::Custom("Failed to convert value from postgres primitive".to_string()))?,
        })
    }
}

impl carbon_core::postgres::operations::Table for crate::accounts::user_position::UserPosition {
    fn table() -> &'static str {
        "user_position_account"
    }

    fn columns() -> Vec<&'static str> {
        vec![
            "__pubkey",
            "__slot",
            "owner",
            "pair",
            "collateral0_applied_min_cf_bps",
            "collateral1_applied_min_cf_bps",
            "collateral0",
            "collateral1",
            "debt0_shares",
            "debt1_shares",
            "bump",
        ]
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Insert for UserPositionRow {
    async fn insert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(r#"
            INSERT INTO user_position_account (
                "owner",
                "pair",
                "collateral0_applied_min_cf_bps",
                "collateral1_applied_min_cf_bps",
                "collateral0",
                "collateral1",
                "debt0_shares",
                "debt1_shares",
                "bump",
                __pubkey, __slot
            ) VALUES (
                $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
            )"#)
        .bind(self.owner.clone())
        .bind(self.pair.clone())
        .bind(self.collateral0_applied_min_cf_bps.clone())
        .bind(self.collateral1_applied_min_cf_bps.clone())
        .bind(self.collateral0.clone())
        .bind(self.collateral1.clone())
        .bind(self.debt0_shares.clone())
        .bind(self.debt1_shares.clone())
        .bind(self.bump.clone())
        .bind(self.account_metadata.pubkey.clone())
        .bind(self.account_metadata.slot.clone())
        .execute(pool).await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Upsert for UserPositionRow {
    async fn upsert(&self, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(r#"INSERT INTO user_position_account (
                "owner",
                "pair",
                "collateral0_applied_min_cf_bps",
                "collateral1_applied_min_cf_bps",
                "collateral0",
                "collateral1",
                "debt0_shares",
                "debt1_shares",
                "bump",
                __pubkey, __slot
            ) VALUES (
                $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
            ) ON CONFLICT (
                __pubkey
            ) DO UPDATE SET
                "owner" = EXCLUDED."owner",
                "pair" = EXCLUDED."pair",
                "collateral0_applied_min_cf_bps" = EXCLUDED."collateral0_applied_min_cf_bps",
                "collateral1_applied_min_cf_bps" = EXCLUDED."collateral1_applied_min_cf_bps",
                "collateral0" = EXCLUDED."collateral0",
                "collateral1" = EXCLUDED."collateral1",
                "debt0_shares" = EXCLUDED."debt0_shares",
                "debt1_shares" = EXCLUDED."debt1_shares",
                "bump" = EXCLUDED."bump",
                __slot = EXCLUDED.__slot
            "#)
        .bind(self.owner.clone())
        .bind(self.pair.clone())
        .bind(self.collateral0_applied_min_cf_bps.clone())
        .bind(self.collateral1_applied_min_cf_bps.clone())
        .bind(self.collateral0.clone())
        .bind(self.collateral1.clone())
        .bind(self.debt0_shares.clone())
        .bind(self.debt1_shares.clone())
        .bind(self.bump.clone())
        .bind(self.account_metadata.pubkey)
        .bind(self.account_metadata.slot.clone())
        .execute(pool).await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::Delete for UserPositionRow {
    type Key = carbon_core::postgres::primitives::Pubkey;

    async fn delete(key: Self::Key, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<()> {
        sqlx::query(r#"DELETE FROM user_position_account WHERE
                __pubkey = $1
            "#)
        .bind(key)
        .execute(pool).await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(())
    }
}

#[async_trait::async_trait]
impl carbon_core::postgres::operations::LookUp for UserPositionRow {
    type Key = carbon_core::postgres::primitives::Pubkey;

    async fn lookup(key: Self::Key, pool: &sqlx::PgPool) -> carbon_core::error::CarbonResult<Option<Self>> {
        let row = sqlx::query_as(r#"SELECT * FROM user_position_account WHERE
                __pubkey = $1
            "#)
        .bind(key)
        .fetch_optional(pool).await
        .map_err(|e| carbon_core::error::Error::Custom(e.to_string()))?;
        Ok(row)
    }
}

pub struct UserPositionMigrationOperation;

#[async_trait::async_trait]
impl sqlx_migrator::Operation<sqlx::Postgres> for UserPositionMigrationOperation {
    async fn up(&self, connection: &mut sqlx::PgConnection) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(r#"CREATE TABLE IF NOT EXISTS user_position_account (
                -- Account data
                "owner" BYTEA NOT NULL,
                "pair" BYTEA NOT NULL,
                "collateral0_applied_min_cf_bps" INT4 NOT NULL,
                "collateral1_applied_min_cf_bps" INT4 NOT NULL,
                "collateral0" NUMERIC(20) NOT NULL,
                "collateral1" NUMERIC(20) NOT NULL,
                "debt0_shares" NUMERIC(39) NOT NULL,
                "debt1_shares" NUMERIC(39) NOT NULL,
                "bump" INT2 NOT NULL,
                -- Account metadata
                __pubkey BYTEA NOT NULL,
                __slot NUMERIC(20),
                PRIMARY KEY (__pubkey)
            )"#).execute(connection).await?;
        Ok(())
    }

    async fn down(&self, connection: &mut sqlx::PgConnection) -> Result<(), sqlx_migrator::error::Error> {
        sqlx::query(r#"DROP TABLE IF EXISTS user_position_account"#).execute(connection).await?;
        Ok(())
    }
}
