//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::Pubkey;
use carbon_core::graphql::primitives::U8;
use crate::types::graphql::RevenueDistributionGraphQL;
use crate::types::graphql::RevenueRecipientsGraphQL;
use crate::types::graphql::RevenueShareGraphQL;
use juniper::GraphQLObject;

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "FutarchyAuthority")]
pub struct FutarchyAuthorityGraphQL {
    pub account_metadata: crate::accounts::graphql::AccountMetadataGraphQL,
    pub version: U8,
    pub authority: Pubkey,
    pub recipients: RevenueRecipientsGraphQL,
    pub revenue_share: RevenueShareGraphQL,
    pub revenue_distribution: RevenueDistributionGraphQL,
    pub bump: U8,
}

impl TryFrom<crate::accounts::postgres::FutarchyAuthorityRow> for FutarchyAuthorityGraphQL {
    type Error = carbon_core::error::Error;
    fn try_from(row: crate::accounts::postgres::FutarchyAuthorityRow) -> Result<Self, Self::Error> {
        Ok(Self {
            account_metadata: row.account_metadata.into(),
            version: carbon_core::graphql::primitives::U8((*row.version) as u8),
            authority: carbon_core::graphql::primitives::Pubkey(row.authority.0),
            recipients: row.recipients.0.into(),
            revenue_share: row.revenue_share.0.into(),
            revenue_distribution: row.revenue_distribution.0.into(),
            bump: carbon_core::graphql::primitives::U8((*row.bump) as u8),
        })
    }
}
