//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::Pubkey;
use carbon_core::graphql::primitives::U128;
use carbon_core::graphql::primitives::U64;
use carbon_core::graphql::primitives::U8;
use crate::types::graphql::LastPriceEMAGraphQL;
use crate::types::graphql::VaultBumpsGraphQL;
use juniper::GraphQLObject;

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "Pair")]
pub struct PairGraphQL {
    pub account_metadata: crate::accounts::graphql::AccountMetadataGraphQL,
    pub token0: Pubkey,
    pub token1: Pubkey,
    pub lp_mint: Pubkey,
    pub rate_model: Pubkey,
    pub swap_fee_bps: i32,
    pub half_life: U64,
    pub fixed_cf_bps: Option<i32>,
    pub reserve0: U64,
    pub reserve1: U64,
    pub cash_reserve0: U64,
    pub cash_reserve1: U64,
    pub last_price0_ema: LastPriceEMAGraphQL,
    pub last_price1_ema: LastPriceEMAGraphQL,
    pub last_update: U64,
    pub last_rate0: U64,
    pub last_rate1: U64,
    pub total_debt0: U64,
    pub total_debt1: U64,
    pub total_debt0_shares: U128,
    pub total_debt1_shares: U128,
    pub total_supply: U64,
    pub total_collateral0: U64,
    pub total_collateral1: U64,
    pub token0_decimals: U8,
    pub token1_decimals: U8,
    pub params_hash: Vec<U8>,
    pub version: U8,
    pub bump: U8,
    pub vault_bumps: VaultBumpsGraphQL,
}

impl TryFrom<crate::accounts::postgres::PairRow> for PairGraphQL {
    type Error = carbon_core::error::Error;
    fn try_from(row: crate::accounts::postgres::PairRow) -> Result<Self, Self::Error> {
        Ok(Self {
            account_metadata: row.account_metadata.into(),
            token0: carbon_core::graphql::primitives::Pubkey(row.token0.0),
            token1: carbon_core::graphql::primitives::Pubkey(row.token1.0),
            lp_mint: carbon_core::graphql::primitives::Pubkey(row.lp_mint.0),
            rate_model: carbon_core::graphql::primitives::Pubkey(row.rate_model.0),
            swap_fee_bps: (*row.swap_fee_bps) as i32,
            half_life: carbon_core::graphql::primitives::U64(*row.half_life),
            fixed_cf_bps: row.fixed_cf_bps.map(|v| (*v) as i32),
            reserve0: carbon_core::graphql::primitives::U64(*row.reserve0),
            reserve1: carbon_core::graphql::primitives::U64(*row.reserve1),
            cash_reserve0: carbon_core::graphql::primitives::U64(*row.cash_reserve0),
            cash_reserve1: carbon_core::graphql::primitives::U64(*row.cash_reserve1),
            last_price0_ema: row.last_price0_ema.0.into(),
            last_price1_ema: row.last_price1_ema.0.into(),
            last_update: carbon_core::graphql::primitives::U64(*row.last_update),
            last_rate0: carbon_core::graphql::primitives::U64(*row.last_rate0),
            last_rate1: carbon_core::graphql::primitives::U64(*row.last_rate1),
            total_debt0: carbon_core::graphql::primitives::U64(*row.total_debt0),
            total_debt1: carbon_core::graphql::primitives::U64(*row.total_debt1),
            total_debt0_shares: carbon_core::graphql::primitives::U128(*row.total_debt0_shares),
            total_debt1_shares: carbon_core::graphql::primitives::U128(*row.total_debt1_shares),
            total_supply: carbon_core::graphql::primitives::U64(*row.total_supply),
            total_collateral0: carbon_core::graphql::primitives::U64(*row.total_collateral0),
            total_collateral1: carbon_core::graphql::primitives::U64(*row.total_collateral1),
            token0_decimals: carbon_core::graphql::primitives::U8((*row.token0_decimals) as u8),
            token1_decimals: carbon_core::graphql::primitives::U8((*row.token1_decimals) as u8),
            params_hash: row.params_hash.into_iter().map(|item| carbon_core::graphql::primitives::U8(item)).collect(),
            version: carbon_core::graphql::primitives::U8((*row.version) as u8),
            bump: carbon_core::graphql::primitives::U8((*row.bump) as u8),
            vault_bumps: row.vault_bumps.0.into(),
        })
    }
}
