//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::U64;
use juniper::GraphQLObject;

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "RateModel")]
pub struct RateModelGraphQL {
    pub account_metadata: crate::accounts::graphql::AccountMetadataGraphQL,
    pub exp_rate: U64,
    pub target_util_start: U64,
    pub target_util_end: U64,
}

impl TryFrom<crate::accounts::postgres::RateModelRow> for RateModelGraphQL {
    type Error = carbon_core::error::Error;
    fn try_from(row: crate::accounts::postgres::RateModelRow) -> Result<Self, Self::Error> {
        Ok(Self {
            account_metadata: row.account_metadata.into(),
            exp_rate: carbon_core::graphql::primitives::U64(*row.exp_rate),
            target_util_start: carbon_core::graphql::primitives::U64(*row.target_util_start),
            target_util_end: carbon_core::graphql::primitives::U64(*row.target_util_end),
        })
    }
}
