//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::Pubkey;
use carbon_core::graphql::primitives::U128;
use carbon_core::graphql::primitives::U64;
use carbon_core::graphql::primitives::U8;
use juniper::GraphQLObject;

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "UserPosition")]
pub struct UserPositionGraphQL {
    pub account_metadata: crate::accounts::graphql::AccountMetadataGraphQL,
    pub owner: Pubkey,
    pub pair: Pubkey,
    pub collateral0_applied_min_cf_bps: i32,
    pub collateral1_applied_min_cf_bps: i32,
    pub collateral0: U64,
    pub collateral1: U64,
    pub debt0_shares: U128,
    pub debt1_shares: U128,
    pub bump: U8,
}

impl TryFrom<crate::accounts::postgres::UserPositionRow> for UserPositionGraphQL {
    type Error = carbon_core::error::Error;
    fn try_from(row: crate::accounts::postgres::UserPositionRow) -> Result<Self, Self::Error> {
        Ok(Self {
            account_metadata: row.account_metadata.into(),
            owner: carbon_core::graphql::primitives::Pubkey(row.owner.0),
            pair: carbon_core::graphql::primitives::Pubkey(row.pair.0),
            collateral0_applied_min_cf_bps: (*row.collateral0_applied_min_cf_bps) as i32,
            collateral1_applied_min_cf_bps: (*row.collateral1_applied_min_cf_bps) as i32,
            collateral0: carbon_core::graphql::primitives::U64(*row.collateral0),
            collateral1: carbon_core::graphql::primitives::U64(*row.collateral1),
            debt0_shares: carbon_core::graphql::primitives::U128(*row.debt0_shares),
            debt1_shares: carbon_core::graphql::primitives::U128(*row.debt1_shares),
            bump: carbon_core::graphql::primitives::U8((*row.bump) as u8),
        })
    }
}
