//! This code was AUTOGENERATED using the Codama library.
use solana_pubkey::Pubkey;
pub struct OmnipairDecoder;
pub const PROGRAM_ID: Pubkey = solana_pubkey::Pubkey::from_str_const("omnixgS8fnqHfCcTGKWj6JtKjzpJZ1Y5y9pyFkQDkYE");

pub mod accounts;
pub mod instructions;
pub mod types;
#[cfg(feature = "graphql")]
pub mod graphql;
