//! This code was AUTOGENERATED using the Codama library.
use solana_pubkey::Pubkey;
pub struct OmnipairDecoder;
pub const PROGRAM_ID: Pubkey = solana_pubkey::Pubkey::from_str_const("omni6GVXb6Aqi2W1GG8vbUDg5NoauGhkrqY8kYZhkn8");

pub mod accounts;
pub mod instructions;
pub mod types;
pub mod events;
#[cfg(feature = "graphql")]
pub mod graphql;
