//! This code was AUTOGENERATED using the Codama library.
use crate::OmnipairDecoder;
use crate::PROGRAM_ID;

#[cfg(feature = "postgres")]
pub mod postgres;

#[cfg(feature = "graphql")]
pub mod graphql;

pub mod futarchy_authority;
pub mod pair;
pub mod rate_model;
pub mod user_position;

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "serde", serde(tag = "type", content = "data"))]
pub enum OmnipairAccount {
    FutarchyAuthority(Box<futarchy_authority::FutarchyAuthority>),
    Pair(Box<pair::Pair>),
    RateModel(Box<rate_model::RateModel>),
    UserPosition(Box<user_position::UserPosition>),
}

impl<'a> carbon_core::account::AccountDecoder<'a> for OmnipairDecoder {
    type AccountType = OmnipairAccount;
    
    fn decode_account(
        &self,
        account: &'a solana_account::Account,
    ) -> Option<carbon_core::account::DecodedAccount<Self::AccountType>> {
        if account.owner != PROGRAM_ID {
            return None;
        }
        
        let data = account.data.as_slice();
        
        {
            if let Some(decoded) = futarchy_authority::FutarchyAuthority::decode(data) {
                return Some(carbon_core::account::DecodedAccount {
                    lamports: account.lamports,
                    data: OmnipairAccount::FutarchyAuthority(Box::new(decoded)),
                    owner: account.owner,
                    executable: account.executable,
                    rent_epoch: account.rent_epoch,
                });
            }
        }
        {
            if let Some(decoded) = pair::Pair::decode(data) {
                return Some(carbon_core::account::DecodedAccount {
                    lamports: account.lamports,
                    data: OmnipairAccount::Pair(Box::new(decoded)),
                    owner: account.owner,
                    executable: account.executable,
                    rent_epoch: account.rent_epoch,
                });
            }
        }
        {
            if let Some(decoded) = rate_model::RateModel::decode(data) {
                return Some(carbon_core::account::DecodedAccount {
                    lamports: account.lamports,
                    data: OmnipairAccount::RateModel(Box::new(decoded)),
                    owner: account.owner,
                    executable: account.executable,
                    rent_epoch: account.rent_epoch,
                });
            }
        }
        {
            if let Some(decoded) = user_position::UserPosition::decode(data) {
                return Some(carbon_core::account::DecodedAccount {
                    lamports: account.lamports,
                    data: OmnipairAccount::UserPosition(Box::new(decoded)),
                    owner: account.owner,
                    executable: account.executable,
                    rent_epoch: account.rent_epoch,
                });
            }
        }
        
        None
    }
}

