//! This code was AUTOGENERATED using the Codama library.
use carbon_core::CarbonDeserialize;
use carbon_core::borsh;
use carbon_core::deserialize::CarbonDeserialize;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq)]
pub struct RateModel {
    /// exp_rate: NAD/millisecond (k_real = exp_rate / NAD)
    pub exp_rate: u64,
    /// utilization band edges (NAD-scaled: 0..NAD)
    pub target_util_start: u64,
    pub target_util_end: u64,
}

impl RateModel {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[94, 3, 203, 219, 107, 137, 4, 162] {
            return None;
        }

        let data_slice = data;

        let data_slice = &data_slice[8..];

        Self::deserialize(data_slice)
    }
}
