//! This code was AUTOGENERATED using the Codama library.
use crate::types::graphql::AddLiquidityArgsGraphQL;
use juniper::GraphQLObject;

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "AddLiquidity")]
pub struct AddLiquidityGraphQL {
    pub instruction_metadata: crate::instructions::graphql::InstructionMetadataGraphQL,
    pub args: AddLiquidityArgsGraphQL,
}

impl TryFrom<crate::instructions::postgres::AddLiquidityRow> for AddLiquidityGraphQL {
    type Error = carbon_core::error::Error;
    fn try_from(row: crate::instructions::postgres::AddLiquidityRow) -> Result<Self, Self::Error> {
        Ok(Self {
            instruction_metadata: row.instruction_metadata.into(),
            args: row.args.0.into(),
        })
    }
}
