//! This code was AUTOGENERATED using the Codama library.
use crate::types::graphql::AdjustDebtArgsGraphQL;
use juniper::GraphQLObject;

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "Borrow")]
pub struct BorrowGraphQL {
    pub instruction_metadata: crate::instructions::graphql::InstructionMetadataGraphQL,
    pub args: AdjustDebtArgsGraphQL,
}

impl TryFrom<crate::instructions::postgres::BorrowRow> for BorrowGraphQL {
    type Error = carbon_core::error::Error;
    fn try_from(row: crate::instructions::postgres::BorrowRow) -> Result<Self, Self::Error> {
        Ok(Self {
            instruction_metadata: row.instruction_metadata.into(),
            args: row.args.0.into(),
        })
    }
}
