//! This code was AUTOGENERATED using the Codama library.
use crate::types::graphql::DistributeTokensArgsGraphQL;
use juniper::GraphQLObject;

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "DistributeTokens")]
pub struct DistributeTokensGraphQL {
    pub instruction_metadata: crate::instructions::graphql::InstructionMetadataGraphQL,
    pub args: DistributeTokensArgsGraphQL,
}

impl TryFrom<crate::instructions::postgres::DistributeTokensRow> for DistributeTokensGraphQL {
    type Error = carbon_core::error::Error;
    fn try_from(row: crate::instructions::postgres::DistributeTokensRow) -> Result<Self, Self::Error> {
        Ok(Self {
            instruction_metadata: row.instruction_metadata.into(),
            args: row.args.0.into(),
        })
    }
}
