//! This code was AUTOGENERATED using the Codama library.
use crate::types::graphql::FlashloanArgsGraphQL;
use juniper::GraphQLObject;

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "Flashloan")]
pub struct FlashloanGraphQL {
    pub instruction_metadata: crate::instructions::graphql::InstructionMetadataGraphQL,
    pub args: FlashloanArgsGraphQL,
}

impl TryFrom<crate::instructions::postgres::FlashloanRow> for FlashloanGraphQL {
    type Error = carbon_core::error::Error;
    fn try_from(row: crate::instructions::postgres::FlashloanRow) -> Result<Self, Self::Error> {
        Ok(Self {
            instruction_metadata: row.instruction_metadata.into(),
            args: row.args.0.into(),
        })
    }
}
