//! This code was AUTOGENERATED using the Codama library.
use crate::types::graphql::InitializeAndBootstrapArgsGraphQL;
use juniper::GraphQLObject;

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "Initialize")]
pub struct InitializeGraphQL {
    pub instruction_metadata: crate::instructions::graphql::InstructionMetadataGraphQL,
    pub args: InitializeAndBootstrapArgsGraphQL,
}

impl TryFrom<crate::instructions::postgres::InitializeRow> for InitializeGraphQL {
    type Error = carbon_core::error::Error;
    fn try_from(row: crate::instructions::postgres::InitializeRow) -> Result<Self, Self::Error> {
        Ok(Self {
            instruction_metadata: row.instruction_metadata.into(),
            args: row.args.0.into(),
        })
    }
}
