//! This code was AUTOGENERATED using the Codama library.
use crate::types::graphql::InitFutarchyAuthorityArgsGraphQL;
use juniper::GraphQLObject;

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "InitFutarchyAuthority")]
pub struct InitFutarchyAuthorityGraphQL {
    pub instruction_metadata: crate::instructions::graphql::InstructionMetadataGraphQL,
    pub args: InitFutarchyAuthorityArgsGraphQL,
}

impl TryFrom<crate::instructions::postgres::InitFutarchyAuthorityRow> for InitFutarchyAuthorityGraphQL {
    type Error = carbon_core::error::Error;
    fn try_from(row: crate::instructions::postgres::InitFutarchyAuthorityRow) -> Result<Self, Self::Error> {
        Ok(Self {
            instruction_metadata: row.instruction_metadata.into(),
            args: row.args.0.into(),
        })
    }
}
