//! This code was AUTOGENERATED using the Codama library.
pub mod add_collateral_schema;
pub mod add_liquidity_schema;
pub mod borrow_schema;
pub mod distribute_tokens_schema;
pub mod flashloan_schema;
pub mod init_futarchy_authority_schema;
pub mod initialize_schema;
pub mod remove_collateral_schema;
pub mod remove_liquidity_schema;
pub mod repay_schema;
pub mod swap_schema;
pub mod update_futarchy_authority_schema;
pub mod update_protocol_revenue_schema;
pub mod view_pair_data_schema;
pub mod view_user_position_data_schema;
pub mod cpi_event_schema;

pub use add_collateral_schema::*;
pub use add_liquidity_schema::*;
pub use borrow_schema::*;
pub use distribute_tokens_schema::*;
pub use flashloan_schema::*;
pub use init_futarchy_authority_schema::*;
pub use initialize_schema::*;
pub use remove_collateral_schema::*;
pub use remove_liquidity_schema::*;
pub use repay_schema::*;
pub use swap_schema::*;
pub use update_futarchy_authority_schema::*;
pub use update_protocol_revenue_schema::*;
pub use view_pair_data_schema::*;
pub use view_user_position_data_schema::*;
pub use cpi_event_schema::*;

use juniper::GraphQLObject;

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "InstructionMetadata")]
pub struct InstructionMetadataGraphQL {
    pub signature: String,
    pub instruction_index: carbon_core::graphql::primitives::U32,
    pub stack_height: carbon_core::graphql::primitives::U32,
    pub slot: Option<carbon_core::graphql::primitives::U64>,
}

impl From<carbon_core::postgres::metadata::InstructionRowMetadata> for InstructionMetadataGraphQL {
    fn from(metadata: carbon_core::postgres::metadata::InstructionRowMetadata) -> Self {
        Self {
            signature: metadata.signature,
            instruction_index: carbon_core::graphql::primitives::U32((*metadata.instruction_index) as u32),
            stack_height: carbon_core::graphql::primitives::U32((*metadata.stack_height) as u32),
            slot: metadata
                .slot
                .map(|v| carbon_core::graphql::primitives::U64(*v)),
        }
    }
}

