//! This code was AUTOGENERATED using the Codama library.
use crate::types::graphql::RemoveLiquidityArgsGraphQL;
use juniper::GraphQLObject;

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "RemoveLiquidity")]
pub struct RemoveLiquidityGraphQL {
    pub instruction_metadata: crate::instructions::graphql::InstructionMetadataGraphQL,
    pub args: RemoveLiquidityArgsGraphQL,
}

impl TryFrom<crate::instructions::postgres::RemoveLiquidityRow> for RemoveLiquidityGraphQL {
    type Error = carbon_core::error::Error;
    fn try_from(row: crate::instructions::postgres::RemoveLiquidityRow) -> Result<Self, Self::Error> {
        Ok(Self {
            instruction_metadata: row.instruction_metadata.into(),
            args: row.args.0.into(),
        })
    }
}
