//! This code was AUTOGENERATED using the Codama library.
use crate::types::graphql::AdjustCollateralArgsGraphQL;
use juniper::GraphQLObject;

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "RemoveCollateral")]
pub struct RemoveCollateralGraphQL {
    pub instruction_metadata: crate::instructions::graphql::InstructionMetadataGraphQL,
    pub args: AdjustCollateralArgsGraphQL,
}

impl TryFrom<crate::instructions::postgres::RemoveCollateralRow> for RemoveCollateralGraphQL {
    type Error = carbon_core::error::Error;
    fn try_from(row: crate::instructions::postgres::RemoveCollateralRow) -> Result<Self, Self::Error> {
        Ok(Self {
            instruction_metadata: row.instruction_metadata.into(),
            args: row.args.0.into(),
        })
    }
}
