//! This code was AUTOGENERATED using the Codama library.
use crate::types::graphql::SwapArgsGraphQL;
use juniper::GraphQLObject;

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "Swap")]
pub struct SwapGraphQL {
    pub instruction_metadata: crate::instructions::graphql::InstructionMetadataGraphQL,
    pub args: SwapArgsGraphQL,
}

impl TryFrom<crate::instructions::postgres::SwapRow> for SwapGraphQL {
    type Error = carbon_core::error::Error;
    fn try_from(row: crate::instructions::postgres::SwapRow) -> Result<Self, Self::Error> {
        Ok(Self {
            instruction_metadata: row.instruction_metadata.into(),
            args: row.args.0.into(),
        })
    }
}
