//! This code was AUTOGENERATED using the Codama library.
use crate::types::graphql::UpdateFutarchyAuthorityArgsGraphQL;
use juniper::GraphQLObject;

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "UpdateFutarchyAuthority")]
pub struct UpdateFutarchyAuthorityGraphQL {
    pub instruction_metadata: crate::instructions::graphql::InstructionMetadataGraphQL,
    pub args: UpdateFutarchyAuthorityArgsGraphQL,
}

impl TryFrom<crate::instructions::postgres::UpdateFutarchyAuthorityRow> for UpdateFutarchyAuthorityGraphQL {
    type Error = carbon_core::error::Error;
    fn try_from(row: crate::instructions::postgres::UpdateFutarchyAuthorityRow) -> Result<Self, Self::Error> {
        Ok(Self {
            instruction_metadata: row.instruction_metadata.into(),
            args: row.args.0.into(),
        })
    }
}
