//! This code was AUTOGENERATED using the Codama library.
use crate::types::graphql::UpdateProtocolRevenueArgsGraphQL;
use juniper::GraphQLObject;

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "UpdateProtocolRevenue")]
pub struct UpdateProtocolRevenueGraphQL {
    pub instruction_metadata: crate::instructions::graphql::InstructionMetadataGraphQL,
    pub args: UpdateProtocolRevenueArgsGraphQL,
}

impl TryFrom<crate::instructions::postgres::UpdateProtocolRevenueRow> for UpdateProtocolRevenueGraphQL {
    type Error = carbon_core::error::Error;
    fn try_from(row: crate::instructions::postgres::UpdateProtocolRevenueRow) -> Result<Self, Self::Error> {
        Ok(Self {
            instruction_metadata: row.instruction_metadata.into(),
            args: row.args.0.into(),
        })
    }
}
