//! This code was AUTOGENERATED using the Codama library.
use crate::types::graphql::EmitValueArgsGraphQL;
use crate::types::graphql::PairViewKindGraphQL;
use juniper::GraphQLObject;

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "ViewPairData")]
pub struct ViewPairDataGraphQL {
    pub instruction_metadata: crate::instructions::graphql::InstructionMetadataGraphQL,
    pub getter: PairViewKindGraphQL,
    pub args: EmitValueArgsGraphQL,
}

impl TryFrom<crate::instructions::postgres::ViewPairDataRow> for ViewPairDataGraphQL {
    type Error = carbon_core::error::Error;
    fn try_from(row: crate::instructions::postgres::ViewPairDataRow) -> Result<Self, Self::Error> {
        Ok(Self {
            instruction_metadata: row.instruction_metadata.into(),
            getter: row.getter.0.into(),
            args: row.args.0.into(),
        })
    }
}
