//! This code was AUTOGENERATED using the Codama library.
use crate::types::graphql::UserPositionViewKindGraphQL;
use juniper::GraphQLObject;

#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "ViewUserPositionData")]
pub struct ViewUserPositionDataGraphQL {
    pub instruction_metadata: crate::instructions::graphql::InstructionMetadataGraphQL,
    pub getter: UserPositionViewKindGraphQL,
}

impl TryFrom<crate::instructions::postgres::ViewUserPositionDataRow> for ViewUserPositionDataGraphQL {
    type Error = carbon_core::error::Error;
    fn try_from(row: crate::instructions::postgres::ViewUserPositionDataRow) -> Result<Self, Self::Error> {
        Ok(Self {
            instruction_metadata: row.instruction_metadata.into(),
            getter: row.getter.0.into(),
        })
    }
}
