//! This code was AUTOGENERATED using the Codama library.

use carbon_core::borsh;
use carbon_core::deserialize::ArrangeAccounts;
pub use super::super::events;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, carbon_core::borsh::BorshSerialize, carbon_core::borsh::BorshDeserialize, PartialEq)]
pub enum CpiEvent {
    AdjustCollateralEvent(events::adjust_collateral_event::AdjustCollateralEventEvent),
    AdjustDebtEvent(events::adjust_debt_event::AdjustDebtEventEvent),
    AdjustLiquidityEvent(events::adjust_liquidity_event::AdjustLiquidityEventEvent),
    BurnEvent(events::burn_event::BurnEventEvent),
    FlashloanEvent(events::flashloan_event::FlashloanEventEvent),
    MintEvent(events::mint_event::MintEventEvent),
    PairCreatedEvent(events::pair_created_event::PairCreatedEventEvent),
    SwapEvent(events::swap_event::SwapEventEvent),
    UpdatePairEvent(events::update_pair_event::UpdatePairEventEvent),
    UserLiquidityPositionUpdatedEvent(events::user_liquidity_position_updated_event::UserLiquidityPositionUpdatedEventEvent),
    UserPositionCreatedEvent(events::user_position_created_event::UserPositionCreatedEventEvent),
    UserPositionLiquidatedEvent(events::user_position_liquidated_event::UserPositionLiquidatedEventEvent),
    UserPositionUpdatedEvent(events::user_position_updated_event::UserPositionUpdatedEventEvent),
}

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct CpiEventInstructionAccounts {
    pub program: solana_pubkey::Pubkey,
    pub event_authority: solana_pubkey::Pubkey,
    pub remaining: Vec<solana_instruction::AccountMeta>,
}

impl CpiEvent {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[228, 69, 165, 46, 81, 203, 154, 29] {
            return None;
        }

        let event_data = &data[8..];

                if let Some(decoded) = events::adjust_collateral_event::AdjustCollateralEventEvent::decode(event_data) {
            return Some(CpiEvent::AdjustCollateralEvent(decoded));
        }
                if let Some(decoded) = events::adjust_debt_event::AdjustDebtEventEvent::decode(event_data) {
            return Some(CpiEvent::AdjustDebtEvent(decoded));
        }
                if let Some(decoded) = events::adjust_liquidity_event::AdjustLiquidityEventEvent::decode(event_data) {
            return Some(CpiEvent::AdjustLiquidityEvent(decoded));
        }
                if let Some(decoded) = events::burn_event::BurnEventEvent::decode(event_data) {
            return Some(CpiEvent::BurnEvent(decoded));
        }
                if let Some(decoded) = events::flashloan_event::FlashloanEventEvent::decode(event_data) {
            return Some(CpiEvent::FlashloanEvent(decoded));
        }
                if let Some(decoded) = events::mint_event::MintEventEvent::decode(event_data) {
            return Some(CpiEvent::MintEvent(decoded));
        }
                if let Some(decoded) = events::pair_created_event::PairCreatedEventEvent::decode(event_data) {
            return Some(CpiEvent::PairCreatedEvent(decoded));
        }
                if let Some(decoded) = events::swap_event::SwapEventEvent::decode(event_data) {
            return Some(CpiEvent::SwapEvent(decoded));
        }
                if let Some(decoded) = events::update_pair_event::UpdatePairEventEvent::decode(event_data) {
            return Some(CpiEvent::UpdatePairEvent(decoded));
        }
                if let Some(decoded) = events::user_liquidity_position_updated_event::UserLiquidityPositionUpdatedEventEvent::decode(event_data) {
            return Some(CpiEvent::UserLiquidityPositionUpdatedEvent(decoded));
        }
                if let Some(decoded) = events::user_position_created_event::UserPositionCreatedEventEvent::decode(event_data) {
            return Some(CpiEvent::UserPositionCreatedEvent(decoded));
        }
                if let Some(decoded) = events::user_position_liquidated_event::UserPositionLiquidatedEventEvent::decode(event_data) {
            return Some(CpiEvent::UserPositionLiquidatedEvent(decoded));
        }
                if let Some(decoded) = events::user_position_updated_event::UserPositionUpdatedEventEvent::decode(event_data) {
            return Some(CpiEvent::UserPositionUpdatedEvent(decoded));
        }
                None
    }
}

impl ArrangeAccounts for CpiEvent {
    type ArrangedAccounts = CpiEventInstructionAccounts;

    fn arrange_accounts(
        accounts: &[solana_instruction::AccountMeta],
    ) -> Option<Self::ArrangedAccounts> {
        let [program, event_authority, remaining @ ..] = accounts else {
            return None;
        };

        Some(CpiEventInstructionAccounts {
            program: program.pubkey,
            event_authority: event_authority.pubkey,
            remaining: remaining.to_vec(),
        })
    }
}

