//! This code was AUTOGENERATED using the Codama library.
use carbon_core::CarbonDeserialize;
use carbon_core::account_utils::next_account;
use carbon_core::borsh;
use carbon_core::deserialize::ArrangeAccounts;
use carbon_core::deserialize::CarbonDeserialize;
use crate::types::DistributeTokensArgs;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq)]
pub struct DistributeTokens {
    pub args: DistributeTokensArgs,
}

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct DistributeTokensInstructionAccounts {
    pub futarchy_authority: solana_pubkey::Pubkey,
    pub source_mint: solana_pubkey::Pubkey,
    pub source_token_account: solana_pubkey::Pubkey,
    pub futarchy_treasury_token_account: solana_pubkey::Pubkey,
    pub buybacks_vault_token_account: solana_pubkey::Pubkey,
    pub team_treasury_token_account: solana_pubkey::Pubkey,
    pub token_program: solana_pubkey::Pubkey,
    pub remaining: Vec<solana_instruction::AccountMeta>,
}

impl DistributeTokens {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[105, 69, 130, 52, 196, 28, 176, 120] {
            return None;
        }

        let data_slice = data;

        let data_slice = &data_slice[8..];

        Self::deserialize(data_slice)
    }
}

impl ArrangeAccounts for DistributeTokens {
    type ArrangedAccounts = DistributeTokensInstructionAccounts;

    fn arrange_accounts(
        accounts: &[solana_instruction::AccountMeta],
    ) -> Option<Self::ArrangedAccounts> {
        let mut iter = accounts.iter();

        let futarchy_authority = next_account(&mut iter)?;
        let source_mint = next_account(&mut iter)?;
        let source_token_account = next_account(&mut iter)?;
        let futarchy_treasury_token_account = next_account(&mut iter)?;
        let buybacks_vault_token_account = next_account(&mut iter)?;
        let team_treasury_token_account = next_account(&mut iter)?;
        let token_program = next_account(&mut iter)?;

        let remaining = iter.as_slice();

        Some(DistributeTokensInstructionAccounts {
            futarchy_authority,
            source_mint,
            source_token_account,
            futarchy_treasury_token_account,
            buybacks_vault_token_account,
            team_treasury_token_account,
            token_program,
            remaining: remaining.to_vec(),
        })
    }
}
