//! This code was AUTOGENERATED using the Codama library.
use carbon_core::CarbonDeserialize;
use carbon_core::account_utils::next_account;
use carbon_core::borsh;
use carbon_core::deserialize::ArrangeAccounts;
use carbon_core::deserialize::CarbonDeserialize;
use crate::types::InitializeAndBootstrapArgs;

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, Clone, borsh::BorshSerialize, CarbonDeserialize, PartialEq)]
pub struct Initialize {
    pub args: InitializeAndBootstrapArgs,
}

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct InitializeInstructionAccounts {
    pub deployer: solana_pubkey::Pubkey,
    pub token0_mint: solana_pubkey::Pubkey,
    pub token1_mint: solana_pubkey::Pubkey,
    pub pair: solana_pubkey::Pubkey,
    pub futarchy_authority: solana_pubkey::Pubkey,
    pub rate_model: solana_pubkey::Pubkey,
    pub lp_mint: solana_pubkey::Pubkey,
    pub lp_token_metadata: solana_pubkey::Pubkey,
    pub deployer_lp_token_account: solana_pubkey::Pubkey,
    pub reserve0_vault: solana_pubkey::Pubkey,
    pub reserve1_vault: solana_pubkey::Pubkey,
    pub collateral0_vault: solana_pubkey::Pubkey,
    pub collateral1_vault: solana_pubkey::Pubkey,
    pub deployer_token0_account: solana_pubkey::Pubkey,
    pub deployer_token1_account: solana_pubkey::Pubkey,
    pub authority_wsol_account: solana_pubkey::Pubkey,
    pub system_program: solana_pubkey::Pubkey,
    pub token_program: solana_pubkey::Pubkey,
    pub token2022_program: solana_pubkey::Pubkey,
    pub token_metadata_program: solana_pubkey::Pubkey,
    pub associated_token_program: solana_pubkey::Pubkey,
    pub rent: solana_pubkey::Pubkey,
    pub event_authority: solana_pubkey::Pubkey,
    pub program: solana_pubkey::Pubkey,
    pub remaining: Vec<solana_instruction::AccountMeta>,
}

impl Initialize {
    pub fn decode(data: &[u8]) -> Option<Self> {
        if data.len() < 8 {
            return None;
        }
        let discriminator = &data[0..8];
        if discriminator != &[175, 175, 109, 31, 13, 152, 155, 237] {
            return None;
        }

        let data_slice = data;

        let data_slice = &data_slice[8..];

        Self::deserialize(data_slice)
    }
}

impl ArrangeAccounts for Initialize {
    type ArrangedAccounts = InitializeInstructionAccounts;

    fn arrange_accounts(
        accounts: &[solana_instruction::AccountMeta],
    ) -> Option<Self::ArrangedAccounts> {
        let mut iter = accounts.iter();

        let deployer = next_account(&mut iter)?;
        let token0_mint = next_account(&mut iter)?;
        let token1_mint = next_account(&mut iter)?;
        let pair = next_account(&mut iter)?;
        let futarchy_authority = next_account(&mut iter)?;
        let rate_model = next_account(&mut iter)?;
        let lp_mint = next_account(&mut iter)?;
        let lp_token_metadata = next_account(&mut iter)?;
        let deployer_lp_token_account = next_account(&mut iter)?;
        let reserve0_vault = next_account(&mut iter)?;
        let reserve1_vault = next_account(&mut iter)?;
        let collateral0_vault = next_account(&mut iter)?;
        let collateral1_vault = next_account(&mut iter)?;
        let deployer_token0_account = next_account(&mut iter)?;
        let deployer_token1_account = next_account(&mut iter)?;
        let authority_wsol_account = next_account(&mut iter)?;
        let system_program = next_account(&mut iter)?;
        let token_program = next_account(&mut iter)?;
        let token2022_program = next_account(&mut iter)?;
        let token_metadata_program = next_account(&mut iter)?;
        let associated_token_program = next_account(&mut iter)?;
        let rent = next_account(&mut iter)?;
        let event_authority = next_account(&mut iter)?;
        let program = next_account(&mut iter)?;

        let remaining = iter.as_slice();

        Some(InitializeInstructionAccounts {
            deployer,
            token0_mint,
            token1_mint,
            pair,
            futarchy_authority,
            rate_model,
            lp_mint,
            lp_token_metadata,
            deployer_lp_token_account,
            reserve0_vault,
            reserve1_vault,
            collateral0_vault,
            collateral1_vault,
            deployer_token0_account,
            deployer_token1_account,
            authority_wsol_account,
            system_program,
            token_program,
            token2022_program,
            token_metadata_program,
            associated_token_program,
            rent,
            event_authority,
            program,
            remaining: remaining.to_vec(),
        })
    }
}
