//! This code was AUTOGENERATED using the Codama library.
use crate::OmnipairDecoder;
use crate::PROGRAM_ID;
#[cfg(feature = "postgres")]
pub mod postgres;

#[cfg(feature = "graphql")]
pub mod graphql;

pub mod add_collateral;
pub mod add_liquidity;
pub mod borrow;
pub mod claim_protocol_fees;
pub mod distribute_tokens;
pub mod flashloan;
pub mod init_futarchy_authority;
pub mod initialize;
pub mod liquidate;
pub mod remove_collateral;
pub mod remove_liquidity;
pub mod repay;
pub mod swap;
pub mod update_futarchy_authority;
pub mod update_protocol_revenue;
pub mod view_pair_data;
pub mod view_user_position_data;
pub mod cpi_event;

pub use self::add_collateral::*;
pub use self::add_liquidity::*;
pub use self::borrow::*;
pub use self::claim_protocol_fees::*;
pub use self::distribute_tokens::*;
pub use self::flashloan::*;
pub use self::init_futarchy_authority::*;
pub use self::initialize::*;
pub use self::liquidate::*;
pub use self::remove_collateral::*;
pub use self::remove_liquidity::*;
pub use self::repay::*;
pub use self::swap::*;
pub use self::update_futarchy_authority::*;
pub use self::update_protocol_revenue::*;
pub use self::view_pair_data::*;
pub use self::view_user_position_data::*;
pub use self::cpi_event::*;

#[derive(Debug, Clone, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "serde", serde(tag = "type", content = "data"))]
pub enum OmnipairInstruction {
    AddCollateral(AddCollateral),
    AddLiquidity(AddLiquidity),
    Borrow(Borrow),
    ClaimProtocolFees(ClaimProtocolFees),
    DistributeTokens(DistributeTokens),
    Flashloan(Flashloan),
    InitFutarchyAuthority(InitFutarchyAuthority),
    Initialize(Initialize),
    Liquidate(Liquidate),
    RemoveCollateral(RemoveCollateral),
    RemoveLiquidity(RemoveLiquidity),
    Repay(Repay),
    Swap(Swap),
    UpdateFutarchyAuthority(UpdateFutarchyAuthority),
    UpdateProtocolRevenue(UpdateProtocolRevenue),
    ViewPairData(ViewPairData),
    ViewUserPositionData(ViewUserPositionData),
    // Anchor CPI Event Instruction
    CpiEvent(CpiEvent)
}

impl carbon_core::instruction::InstructionDecoder<'_> for OmnipairDecoder {
    type InstructionType = OmnipairInstruction;

    fn decode_instruction(
        &self,
        instruction: &solana_instruction::Instruction,
    ) -> Option<carbon_core::instruction::DecodedInstruction<Self::InstructionType>> {
        if !instruction.program_id.eq(&PROGRAM_ID) {
            return None;
        }

        let data = instruction.data.as_slice();

        {
            if let Some(decoded) = add_collateral::AddCollateral::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: OmnipairInstruction::AddCollateral(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = add_liquidity::AddLiquidity::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: OmnipairInstruction::AddLiquidity(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = borrow::Borrow::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: OmnipairInstruction::Borrow(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = claim_protocol_fees::ClaimProtocolFees::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: OmnipairInstruction::ClaimProtocolFees(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = distribute_tokens::DistributeTokens::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: OmnipairInstruction::DistributeTokens(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = flashloan::Flashloan::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: OmnipairInstruction::Flashloan(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = init_futarchy_authority::InitFutarchyAuthority::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: OmnipairInstruction::InitFutarchyAuthority(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = initialize::Initialize::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: OmnipairInstruction::Initialize(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = liquidate::Liquidate::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: OmnipairInstruction::Liquidate(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = remove_collateral::RemoveCollateral::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: OmnipairInstruction::RemoveCollateral(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = remove_liquidity::RemoveLiquidity::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: OmnipairInstruction::RemoveLiquidity(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = repay::Repay::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: OmnipairInstruction::Repay(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = swap::Swap::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: OmnipairInstruction::Swap(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = update_futarchy_authority::UpdateFutarchyAuthority::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: OmnipairInstruction::UpdateFutarchyAuthority(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = update_protocol_revenue::UpdateProtocolRevenue::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: OmnipairInstruction::UpdateProtocolRevenue(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = view_pair_data::ViewPairData::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: OmnipairInstruction::ViewPairData(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = view_user_position_data::ViewUserPositionData::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: OmnipairInstruction::ViewUserPositionData(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }
        {
            if let Some(decoded) = cpi_event::CpiEvent::decode(data) {
                return Some(carbon_core::instruction::DecodedInstruction {
                    program_id: instruction.program_id,
                    data: OmnipairInstruction::CpiEvent(decoded),
                    accounts: instruction.accounts.clone(),
                });
            }
        }

        None
    }
}
