name: anchor-test
on:
  push:
    branches:
      - develop
      - production
  pull_request:

jobs:
  run-anchor-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: metadaoproject/anchor-test@v2.1
        with:
            anchor-version: '0.31.0'
            solana-cli-version: '1.18.18'