//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::U64;
use juniper::GraphQLObject;
#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "AddLiquidityArgs")]
pub struct AddLiquidityArgsGraphQL {
    pub amount0_in: U64,
    pub amount1_in: U64,
    pub min_liquidity_out: U64,
}

impl From<crate::types::AddLiquidityArgs> for AddLiquidityArgsGraphQL {
    fn from(original: crate::types::AddLiquidityArgs) -> Self {
        Self {
            amount0_in: carbon_core::graphql::primitives::U64(original.amount0_in),
            amount1_in: carbon_core::graphql::primitives::U64(original.amount1_in),
            min_liquidity_out: carbon_core::graphql::primitives::U64(original.min_liquidity_out),
        }
    }
}
