//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::U64;
use juniper::GraphQLObject;
#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "AdjustDebtArgs")]
pub struct AdjustDebtArgsGraphQL {
    pub amount: U64,
}

impl From<crate::types::AdjustDebtArgs> for AdjustDebtArgsGraphQL {
    fn from(original: crate::types::AdjustDebtArgs) -> Self {
        Self {
            amount: carbon_core::graphql::primitives::U64(original.amount),
        }
    }
}
