//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::I64;
use crate::types::graphql::EventMetadataGraphQL;
use juniper::GraphQLObject;
#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "AdjustCollateralEvent")]
pub struct AdjustCollateralEventGraphQL {
    pub amount0: I64,
    pub amount1: I64,
    pub metadata: EventMetadataGraphQL,
}

impl From<crate::types::AdjustCollateralEvent> for AdjustCollateralEventGraphQL {
    fn from(original: crate::types::AdjustCollateralEvent) -> Self {
        Self {
            amount0: carbon_core::graphql::primitives::I64(original.amount0),
            amount1: carbon_core::graphql::primitives::I64(original.amount1),
            metadata: original.metadata.into(),
        }
    }
}
