//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::U64;
use crate::types::graphql::EventMetadataGraphQL;
use juniper::GraphQLObject;
#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "AdjustLiquidityEvent")]
pub struct AdjustLiquidityEventGraphQL {
    pub amount0: U64,
    pub amount1: U64,
    pub liquidity: U64,
    pub metadata: EventMetadataGraphQL,
}

impl From<crate::types::AdjustLiquidityEvent> for AdjustLiquidityEventGraphQL {
    fn from(original: crate::types::AdjustLiquidityEvent) -> Self {
        Self {
            amount0: carbon_core::graphql::primitives::U64(original.amount0),
            amount1: carbon_core::graphql::primitives::U64(original.amount1),
            liquidity: carbon_core::graphql::primitives::U64(original.liquidity),
            metadata: original.metadata.into(),
        }
    }
}
