//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::U64;
use juniper::GraphQLObject;
#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "AdjustCollateralArgs")]
pub struct AdjustCollateralArgsGraphQL {
    pub amount: U64,
}

impl From<crate::types::AdjustCollateralArgs> for AdjustCollateralArgsGraphQL {
    fn from(original: crate::types::AdjustCollateralArgs) -> Self {
        Self {
            amount: carbon_core::graphql::primitives::U64(original.amount),
        }
    }
}
