//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::Json;

// Empty struct exposed as Json in GraphQL
pub type DistributeTokensArgsGraphQL = Json;

impl From<crate::types::DistributeTokensArgs> for DistributeTokensArgsGraphQL {
    fn from(_original: crate::types::DistributeTokensArgs) -> Self {
        carbon_core::graphql::primitives::Json(
            serde_json::Value::Null,
        )
    }
}

