//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::Pubkey;
use carbon_core::graphql::primitives::U64;
use juniper::GraphQLObject;
#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "EmitValueArgs")]
pub struct EmitValueArgsGraphQL {
    pub debt_amount: Option<U64>,
    pub collateral_amount: Option<U64>,
    pub collateral_token: Option<Pubkey>,
}

impl From<crate::types::EmitValueArgs> for EmitValueArgsGraphQL {
    fn from(original: crate::types::EmitValueArgs) -> Self {
        Self {
            debt_amount: original.debt_amount.map(|v| carbon_core::graphql::primitives::U64(v)),
            collateral_amount: original.collateral_amount.map(|v| carbon_core::graphql::primitives::U64(v)),
            collateral_token: original.collateral_token.map(|v| carbon_core::graphql::primitives::Pubkey(v)),
        }
    }
}
