//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::Pubkey;
use carbon_core::graphql::primitives::U64;
use juniper::GraphQLObject;
#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "EventMetadata")]
pub struct EventMetadataGraphQL {
    pub signer: Pubkey,
    pub pair: Pubkey,
    pub slot: U64,
}

impl From<crate::types::EventMetadata> for EventMetadataGraphQL {
    fn from(original: crate::types::EventMetadata) -> Self {
        Self {
            signer: carbon_core::graphql::primitives::Pubkey(original.signer),
            pair: carbon_core::graphql::primitives::Pubkey(original.pair),
            slot: carbon_core::graphql::primitives::U64(original.slot),
        }
    }
}
