//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::U64;
use carbon_core::graphql::primitives::U8;
use juniper::GraphQLObject;
#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "FlashloanArgs")]
pub struct FlashloanArgsGraphQL {
    pub amount0: U64,
    pub amount1: U64,
    pub data: Vec<U8>,
}

impl From<crate::types::FlashloanArgs> for FlashloanArgsGraphQL {
    fn from(original: crate::types::FlashloanArgs) -> Self {
        Self {
            amount0: carbon_core::graphql::primitives::U64(original.amount0),
            amount1: carbon_core::graphql::primitives::U64(original.amount1),
            data: original.data.into_iter().map(|item| carbon_core::graphql::primitives::U8(item)).collect(),
        }
    }
}
