//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::Pubkey;
use carbon_core::graphql::primitives::U64;
use crate::types::graphql::EventMetadataGraphQL;
use juniper::GraphQLObject;
#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "FlashloanEvent")]
pub struct FlashloanEventGraphQL {
    pub amount0: U64,
    pub amount1: U64,
    pub fee0: U64,
    pub fee1: U64,
    pub receiver: Pubkey,
    pub metadata: EventMetadataGraphQL,
}

impl From<crate::types::FlashloanEvent> for FlashloanEventGraphQL {
    fn from(original: crate::types::FlashloanEvent) -> Self {
        Self {
            amount0: carbon_core::graphql::primitives::U64(original.amount0),
            amount1: carbon_core::graphql::primitives::U64(original.amount1),
            fee0: carbon_core::graphql::primitives::U64(original.fee0),
            fee1: carbon_core::graphql::primitives::U64(original.fee1),
            receiver: carbon_core::graphql::primitives::Pubkey(original.receiver),
            metadata: original.metadata.into(),
        }
    }
}
