//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::U64;
use carbon_core::graphql::primitives::U8;
use juniper::GraphQLObject;
#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "InitializeAndBootstrapArgs")]
pub struct InitializeAndBootstrapArgsGraphQL {
    pub swap_fee_bps: i32,
    pub half_life: U64,
    pub fixed_cf_bps: Option<i32>,
    pub target_util_start_bps: Option<U64>,
    pub target_util_end_bps: Option<U64>,
    pub params_hash: Vec<U8>,
    pub version: U8,
    pub amount0_in: U64,
    pub amount1_in: U64,
    pub min_liquidity_out: U64,
    pub lp_name: String,
    pub lp_symbol: String,
    pub lp_uri: String,
}

impl From<crate::types::InitializeAndBootstrapArgs> for InitializeAndBootstrapArgsGraphQL {
    fn from(original: crate::types::InitializeAndBootstrapArgs) -> Self {
        Self {
            swap_fee_bps: original.swap_fee_bps as i32,
            half_life: carbon_core::graphql::primitives::U64(original.half_life),
            fixed_cf_bps: original.fixed_cf_bps.map(|v| v as i32),
            target_util_start_bps: original.target_util_start_bps.map(|v| carbon_core::graphql::primitives::U64(v)),
            target_util_end_bps: original.target_util_end_bps.map(|v| carbon_core::graphql::primitives::U64(v)),
            params_hash: original.params_hash.into_iter().map(|item| carbon_core::graphql::primitives::U8(item)).collect(),
            version: carbon_core::graphql::primitives::U8(original.version),
            amount0_in: carbon_core::graphql::primitives::U64(original.amount0_in),
            amount1_in: carbon_core::graphql::primitives::U64(original.amount1_in),
            min_liquidity_out: carbon_core::graphql::primitives::U64(original.min_liquidity_out),
            lp_name: original.lp_name,
            lp_symbol: original.lp_symbol,
            lp_uri: original.lp_uri,
        }
    }
}
