//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::Pubkey;
use juniper::GraphQLObject;
#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "InitFutarchyAuthorityArgs")]
pub struct InitFutarchyAuthorityArgsGraphQL {
    pub authority: Pubkey,
    pub swap_bps: i32,
    pub interest_bps: i32,
    pub futarchy_treasury: Pubkey,
    pub futarchy_treasury_bps: i32,
    pub buybacks_vault: Pubkey,
    pub buybacks_vault_bps: i32,
    pub team_treasury: Pubkey,
    pub team_treasury_bps: i32,
}

impl From<crate::types::InitFutarchyAuthorityArgs> for InitFutarchyAuthorityArgsGraphQL {
    fn from(original: crate::types::InitFutarchyAuthorityArgs) -> Self {
        Self {
            authority: carbon_core::graphql::primitives::Pubkey(original.authority),
            swap_bps: original.swap_bps as i32,
            interest_bps: original.interest_bps as i32,
            futarchy_treasury: carbon_core::graphql::primitives::Pubkey(original.futarchy_treasury),
            futarchy_treasury_bps: original.futarchy_treasury_bps as i32,
            buybacks_vault: carbon_core::graphql::primitives::Pubkey(original.buybacks_vault),
            buybacks_vault_bps: original.buybacks_vault_bps as i32,
            team_treasury: carbon_core::graphql::primitives::Pubkey(original.team_treasury),
            team_treasury_bps: original.team_treasury_bps as i32,
        }
    }
}
