//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::U64;
use juniper::GraphQLObject;
#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "LastPriceEMA")]
pub struct LastPriceEMAGraphQL {
    pub symmetric: U64,
    pub directional: U64,
}

impl From<crate::types::LastPriceEMA> for LastPriceEMAGraphQL {
    fn from(original: crate::types::LastPriceEMA) -> Self {
        Self {
            symmetric: carbon_core::graphql::primitives::U64(original.symmetric),
            directional: carbon_core::graphql::primitives::U64(original.directional),
        }
    }
}
