//! This code was AUTOGENERATED using the Codama library.
use juniper::GraphQLEnum;

/// Enum for the different getters that can be emitted
/// This is used to eliminate off-chain calculations / simulation
#[derive(Debug, Clone, GraphQLEnum)]
#[graphql(name = "PairViewKind")]
pub enum PairViewKindGraphQL {
        EmaPrice0Nad,
        EmaPrice1Nad,
        SpotPrice0Nad,
        SpotPrice1Nad,
        K,
        GetRates,
        GetBorrowLimitAndCfBpsForCollateral,
}

impl From<crate::types::PairViewKind> for PairViewKindGraphQL {
    fn from(original: crate::types::PairViewKind) -> Self {
        match original {
            crate::types::PairViewKind::EmaPrice0Nad => Self::EmaPrice0Nad,
            crate::types::PairViewKind::EmaPrice1Nad => Self::EmaPrice1Nad,
            crate::types::PairViewKind::SpotPrice0Nad => Self::SpotPrice0Nad,
            crate::types::PairViewKind::SpotPrice1Nad => Self::SpotPrice1Nad,
            crate::types::PairViewKind::K => Self::K,
            crate::types::PairViewKind::GetRates => Self::GetRates,
            crate::types::PairViewKind::GetBorrowLimitAndCfBpsForCollateral => Self::GetBorrowLimitAndCfBpsForCollateral,
        }
    }
}

