//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::Pubkey;
use carbon_core::graphql::primitives::U64;
use carbon_core::graphql::primitives::U8;
use crate::types::graphql::EventMetadataGraphQL;
use juniper::GraphQLObject;
#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "PairCreatedEvent")]
pub struct PairCreatedEventGraphQL {
    pub token0: Pubkey,
    pub token1: Pubkey,
    pub lp_mint: Pubkey,
    pub token0_decimals: U8,
    pub token1_decimals: U8,
    pub rate_model: Pubkey,
    pub swap_fee_bps: i32,
    pub half_life: U64,
    pub fixed_cf_bps: Option<i32>,
    pub params_hash: Vec<U8>,
    pub version: U8,
    pub metadata: EventMetadataGraphQL,
}

impl From<crate::types::PairCreatedEvent> for PairCreatedEventGraphQL {
    fn from(original: crate::types::PairCreatedEvent) -> Self {
        Self {
            token0: carbon_core::graphql::primitives::Pubkey(original.token0),
            token1: carbon_core::graphql::primitives::Pubkey(original.token1),
            lp_mint: carbon_core::graphql::primitives::Pubkey(original.lp_mint),
            token0_decimals: carbon_core::graphql::primitives::U8(original.token0_decimals),
            token1_decimals: carbon_core::graphql::primitives::U8(original.token1_decimals),
            rate_model: carbon_core::graphql::primitives::Pubkey(original.rate_model),
            swap_fee_bps: original.swap_fee_bps as i32,
            half_life: carbon_core::graphql::primitives::U64(original.half_life),
            fixed_cf_bps: original.fixed_cf_bps.map(|v| v as i32),
            params_hash: original.params_hash.into_iter().map(|item| carbon_core::graphql::primitives::U8(item)).collect(),
            version: carbon_core::graphql::primitives::U8(original.version),
            metadata: original.metadata.into(),
        }
    }
}
