//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::U64;
use juniper::GraphQLObject;
#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "RemoveLiquidityArgs")]
pub struct RemoveLiquidityArgsGraphQL {
    pub liquidity_in: U64,
    pub min_amount0_out: U64,
    pub min_amount1_out: U64,
}

impl From<crate::types::RemoveLiquidityArgs> for RemoveLiquidityArgsGraphQL {
    fn from(original: crate::types::RemoveLiquidityArgs) -> Self {
        Self {
            liquidity_in: carbon_core::graphql::primitives::U64(original.liquidity_in),
            min_amount0_out: carbon_core::graphql::primitives::U64(original.min_amount0_out),
            min_amount1_out: carbon_core::graphql::primitives::U64(original.min_amount1_out),
        }
    }
}
