//! This code was AUTOGENERATED using the Codama library.
use juniper::GraphQLObject;
#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "RevenueShare")]
pub struct RevenueShareGraphQL {
    pub swap_bps: i32,
    pub interest_bps: i32,
}

impl From<crate::types::RevenueShare> for RevenueShareGraphQL {
    fn from(original: crate::types::RevenueShare) -> Self {
        Self {
            swap_bps: original.swap_bps as i32,
            interest_bps: original.interest_bps as i32,
        }
    }
}
