//! This code was AUTOGENERATED using the Codama library.
use juniper::GraphQLObject;
#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "RevenueDistribution")]
pub struct RevenueDistributionGraphQL {
    pub futarchy_treasury_bps: i32,
    pub buybacks_vault_bps: i32,
    pub team_treasury_bps: i32,
}

impl From<crate::types::RevenueDistribution> for RevenueDistributionGraphQL {
    fn from(original: crate::types::RevenueDistribution) -> Self {
        Self {
            futarchy_treasury_bps: original.futarchy_treasury_bps as i32,
            buybacks_vault_bps: original.buybacks_vault_bps as i32,
            team_treasury_bps: original.team_treasury_bps as i32,
        }
    }
}
