//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::Pubkey;
use juniper::GraphQLObject;
#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "RevenueRecipients")]
pub struct RevenueRecipientsGraphQL {
    pub futarchy_treasury: Pubkey,
    pub buybacks_vault: Pubkey,
    pub team_treasury: Pubkey,
}

impl From<crate::types::RevenueRecipients> for RevenueRecipientsGraphQL {
    fn from(original: crate::types::RevenueRecipients) -> Self {
        Self {
            futarchy_treasury: carbon_core::graphql::primitives::Pubkey(original.futarchy_treasury),
            buybacks_vault: carbon_core::graphql::primitives::Pubkey(original.buybacks_vault),
            team_treasury: carbon_core::graphql::primitives::Pubkey(original.team_treasury),
        }
    }
}
