//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::U64;
use juniper::GraphQLObject;
#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "SwapArgs")]
pub struct SwapArgsGraphQL {
    pub amount_in: U64,
    pub min_amount_out: U64,
}

impl From<crate::types::SwapArgs> for SwapArgsGraphQL {
    fn from(original: crate::types::SwapArgs) -> Self {
        Self {
            amount_in: carbon_core::graphql::primitives::U64(original.amount_in),
            min_amount_out: carbon_core::graphql::primitives::U64(original.min_amount_out),
        }
    }
}
