//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::U64;
use crate::types::graphql::EventMetadataGraphQL;
use juniper::GraphQLObject;
#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "SwapEvent")]
pub struct SwapEventGraphQL {
    pub reserve0: U64,
    pub reserve1: U64,
    pub is_token0_in: bool,
    pub amount_in: U64,
    pub amount_out: U64,
    pub amount_in_after_fee: U64,
    pub metadata: EventMetadataGraphQL,
}

impl From<crate::types::SwapEvent> for SwapEventGraphQL {
    fn from(original: crate::types::SwapEvent) -> Self {
        Self {
            reserve0: carbon_core::graphql::primitives::U64(original.reserve0),
            reserve1: carbon_core::graphql::primitives::U64(original.reserve1),
            is_token0_in: original.is_token0_in,
            amount_in: carbon_core::graphql::primitives::U64(original.amount_in),
            amount_out: carbon_core::graphql::primitives::U64(original.amount_out),
            amount_in_after_fee: carbon_core::graphql::primitives::U64(original.amount_in_after_fee),
            metadata: original.metadata.into(),
        }
    }
}
