//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::Pubkey;
use juniper::GraphQLObject;
#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "UpdateFutarchyAuthorityArgs")]
pub struct UpdateFutarchyAuthorityArgsGraphQL {
    pub new_authority: Pubkey,
}

impl From<crate::types::UpdateFutarchyAuthorityArgs> for UpdateFutarchyAuthorityArgsGraphQL {
    fn from(original: crate::types::UpdateFutarchyAuthorityArgs) -> Self {
        Self {
            new_authority: carbon_core::graphql::primitives::Pubkey(original.new_authority),
        }
    }
}
