//! This code was AUTOGENERATED using the Codama library.
use crate::types::graphql::RevenueDistributionGraphQL;
use juniper::GraphQLObject;
#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "UpdateProtocolRevenueArgs")]
pub struct UpdateProtocolRevenueArgsGraphQL {
    pub swap_bps: Option<i32>,
    pub interest_bps: Option<i32>,
    pub revenue_distribution: Option<RevenueDistributionGraphQL>,
}

impl From<crate::types::UpdateProtocolRevenueArgs> for UpdateProtocolRevenueArgsGraphQL {
    fn from(original: crate::types::UpdateProtocolRevenueArgs) -> Self {
        Self {
            swap_bps: original.swap_bps.map(|v| v as i32),
            interest_bps: original.interest_bps.map(|v| v as i32),
            revenue_distribution: original.revenue_distribution.map(|v| v.into()),
        }
    }
}
