//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::U128;
use carbon_core::graphql::primitives::U64;
use crate::types::graphql::EventMetadataGraphQL;
use juniper::GraphQLObject;
#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "UpdatePairEvent")]
pub struct UpdatePairEventGraphQL {
    pub price0_ema: U64,
    pub price1_ema: U64,
    pub rate0: U64,
    pub rate1: U64,
    pub accrued_interest0: U128,
    pub accrued_interest1: U128,
    pub cash_reserve0: U64,
    pub cash_reserve1: U64,
    pub reserve0_after_interest: U64,
    pub reserve1_after_interest: U64,
    pub metadata: EventMetadataGraphQL,
}

impl From<crate::types::UpdatePairEvent> for UpdatePairEventGraphQL {
    fn from(original: crate::types::UpdatePairEvent) -> Self {
        Self {
            price0_ema: carbon_core::graphql::primitives::U64(original.price0_ema),
            price1_ema: carbon_core::graphql::primitives::U64(original.price1_ema),
            rate0: carbon_core::graphql::primitives::U64(original.rate0),
            rate1: carbon_core::graphql::primitives::U64(original.rate1),
            accrued_interest0: carbon_core::graphql::primitives::U128(original.accrued_interest0),
            accrued_interest1: carbon_core::graphql::primitives::U128(original.accrued_interest1),
            cash_reserve0: carbon_core::graphql::primitives::U64(original.cash_reserve0),
            cash_reserve1: carbon_core::graphql::primitives::U64(original.cash_reserve1),
            reserve0_after_interest: carbon_core::graphql::primitives::U64(original.reserve0_after_interest),
            reserve1_after_interest: carbon_core::graphql::primitives::U64(original.reserve1_after_interest),
            metadata: original.metadata.into(),
        }
    }
}
