//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::Pubkey;
use carbon_core::graphql::primitives::U64;
use crate::types::graphql::EventMetadataGraphQL;
use juniper::GraphQLObject;
#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "UserLiquidityPositionUpdatedEvent")]
pub struct UserLiquidityPositionUpdatedEventGraphQL {
    pub token0_amount: U64,
    pub token1_amount: U64,
    pub lp_amount: U64,
    pub token0_mint: Pubkey,
    pub token1_mint: Pubkey,
    pub lp_mint: Pubkey,
    pub metadata: EventMetadataGraphQL,
}

impl From<crate::types::UserLiquidityPositionUpdatedEvent> for UserLiquidityPositionUpdatedEventGraphQL {
    fn from(original: crate::types::UserLiquidityPositionUpdatedEvent) -> Self {
        Self {
            token0_amount: carbon_core::graphql::primitives::U64(original.token0_amount),
            token1_amount: carbon_core::graphql::primitives::U64(original.token1_amount),
            lp_amount: carbon_core::graphql::primitives::U64(original.lp_amount),
            token0_mint: carbon_core::graphql::primitives::Pubkey(original.token0_mint),
            token1_mint: carbon_core::graphql::primitives::Pubkey(original.token1_mint),
            lp_mint: carbon_core::graphql::primitives::Pubkey(original.lp_mint),
            metadata: original.metadata.into(),
        }
    }
}
