//! This code was AUTOGENERATED using the Codama library.
use juniper::GraphQLEnum;

#[derive(Debug, Clone, GraphQLEnum)]
#[graphql(name = "UserPositionViewKind")]
pub enum UserPositionViewKindGraphQL {
        UserBorrowingPower,
        UserAppliedCollateralFactorBps,
        UserLiquidationCollateralFactorBps,
        UserDebtUtilizationBps,
        UserLiquidationPrice,
        UserDebtWithInterest,
        UserIsLiquidatable,
}

impl From<crate::types::UserPositionViewKind> for UserPositionViewKindGraphQL {
    fn from(original: crate::types::UserPositionViewKind) -> Self {
        match original {
            crate::types::UserPositionViewKind::UserBorrowingPower => Self::UserBorrowingPower,
            crate::types::UserPositionViewKind::UserAppliedCollateralFactorBps => Self::UserAppliedCollateralFactorBps,
            crate::types::UserPositionViewKind::UserLiquidationCollateralFactorBps => Self::UserLiquidationCollateralFactorBps,
            crate::types::UserPositionViewKind::UserDebtUtilizationBps => Self::UserDebtUtilizationBps,
            crate::types::UserPositionViewKind::UserLiquidationPrice => Self::UserLiquidationPrice,
            crate::types::UserPositionViewKind::UserDebtWithInterest => Self::UserDebtWithInterest,
            crate::types::UserPositionViewKind::UserIsLiquidatable => Self::UserIsLiquidatable,
        }
    }
}

