//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::Pubkey;
use carbon_core::graphql::primitives::U128;
use carbon_core::graphql::primitives::U64;
use crate::types::graphql::EventMetadataGraphQL;
use juniper::GraphQLObject;
#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "UserPositionUpdatedEvent")]
pub struct UserPositionUpdatedEventGraphQL {
    pub position: Pubkey,
    pub collateral0: U64,
    pub collateral1: U64,
    pub debt0_shares: U128,
    pub debt1_shares: U128,
    pub collateral0_applied_min_cf_bps: i32,
    pub collateral1_applied_min_cf_bps: i32,
    pub metadata: EventMetadataGraphQL,
}

impl From<crate::types::UserPositionUpdatedEvent> for UserPositionUpdatedEventGraphQL {
    fn from(original: crate::types::UserPositionUpdatedEvent) -> Self {
        Self {
            position: carbon_core::graphql::primitives::Pubkey(original.position),
            collateral0: carbon_core::graphql::primitives::U64(original.collateral0),
            collateral1: carbon_core::graphql::primitives::U64(original.collateral1),
            debt0_shares: carbon_core::graphql::primitives::U128(original.debt0_shares),
            debt1_shares: carbon_core::graphql::primitives::U128(original.debt1_shares),
            collateral0_applied_min_cf_bps: original.collateral0_applied_min_cf_bps as i32,
            collateral1_applied_min_cf_bps: original.collateral1_applied_min_cf_bps as i32,
            metadata: original.metadata.into(),
        }
    }
}
