//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::Pubkey;
use carbon_core::graphql::primitives::U128;
use carbon_core::graphql::primitives::U64;
use crate::types::graphql::EventMetadataGraphQL;
use juniper::GraphQLObject;
#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "UserPositionLiquidatedEvent")]
pub struct UserPositionLiquidatedEventGraphQL {
    pub position: Pubkey,
    pub liquidator: Pubkey,
    pub collateral0_liquidated: U64,
    pub collateral1_liquidated: U64,
    pub debt0_liquidated: U64,
    pub debt1_liquidated: U64,
    pub collateral_price: U64,
    pub shortfall: U128,
    pub liquidation_bonus_applied: U64,
    pub k0: U128,
    pub k1: U128,
    pub metadata: EventMetadataGraphQL,
}

impl From<crate::types::UserPositionLiquidatedEvent> for UserPositionLiquidatedEventGraphQL {
    fn from(original: crate::types::UserPositionLiquidatedEvent) -> Self {
        Self {
            position: carbon_core::graphql::primitives::Pubkey(original.position),
            liquidator: carbon_core::graphql::primitives::Pubkey(original.liquidator),
            collateral0_liquidated: carbon_core::graphql::primitives::U64(original.collateral0_liquidated),
            collateral1_liquidated: carbon_core::graphql::primitives::U64(original.collateral1_liquidated),
            debt0_liquidated: carbon_core::graphql::primitives::U64(original.debt0_liquidated),
            debt1_liquidated: carbon_core::graphql::primitives::U64(original.debt1_liquidated),
            collateral_price: carbon_core::graphql::primitives::U64(original.collateral_price),
            shortfall: carbon_core::graphql::primitives::U128(original.shortfall),
            liquidation_bonus_applied: carbon_core::graphql::primitives::U64(original.liquidation_bonus_applied),
            k0: carbon_core::graphql::primitives::U128(original.k0),
            k1: carbon_core::graphql::primitives::U128(original.k1),
            metadata: original.metadata.into(),
        }
    }
}
