//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::Pubkey;
use crate::types::graphql::EventMetadataGraphQL;
use juniper::GraphQLObject;
#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "UserPositionCreatedEvent")]
pub struct UserPositionCreatedEventGraphQL {
    pub position: Pubkey,
    pub metadata: EventMetadataGraphQL,
}

impl From<crate::types::UserPositionCreatedEvent> for UserPositionCreatedEventGraphQL {
    fn from(original: crate::types::UserPositionCreatedEvent) -> Self {
        Self {
            position: carbon_core::graphql::primitives::Pubkey(original.position),
            metadata: original.metadata.into(),
        }
    }
}
