//! This code was AUTOGENERATED using the Codama library.
use carbon_core::graphql::primitives::U8;
use juniper::GraphQLObject;
#[derive(Debug, Clone, GraphQLObject)]
#[graphql(name = "VaultBumps")]
pub struct VaultBumpsGraphQL {
    pub reserve0: U8,
    pub reserve1: U8,
    pub collateral0: U8,
    pub collateral1: U8,
}

impl From<crate::types::VaultBumps> for VaultBumpsGraphQL {
    fn from(original: crate::types::VaultBumps) -> Self {
        Self {
            reserve0: carbon_core::graphql::primitives::U8(original.reserve0),
            reserve1: carbon_core::graphql::primitives::U8(original.reserve1),
            collateral0: carbon_core::graphql::primitives::U8(original.collateral0),
            collateral1: carbon_core::graphql::primitives::U8(original.collateral1),
        }
    }
}
